import Dexie, { type EntityTable } from "dexie";
import type { LangCode } from "./languages";

/**
 * IndexedDB schema. Phase 1: source of truth.
 * Phase 2: this becomes the offline cache; Supabase is authoritative.
 *
 * Whenever you change a table shape, BUMP the version number AND add a
 * migration block (see Dexie docs). Don't edit existing version blocks.
 */

// ---------------------------------------------------------------------------
// Settings (single row, id = "me" for Phase 1)
// ---------------------------------------------------------------------------
export interface Settings {
  id: "me";
  nativeLang: LangCode;
  targetLang: LangCode;
  goal: "travel" | "heritage" | "work" | "exam" | "fun";
  dailyMinutes: 5 | 10 | 20;
  cefrLevel: "A1" | "A2" | "B1";
  createdAt: number;
  updatedAt: number;
}

// ---------------------------------------------------------------------------
// Lessons (cached per language pair)
// ---------------------------------------------------------------------------
export interface VocabItem {
  src: string; // word/phrase in source (native) language
  tgt: string; // word/phrase in target language
  translit?: string; // romanization for Geʽez scripts
  imageQuery?: string; // hint for picture lookup
  imageUrl?: string; // cached image URL (filled in lazily)
}

export interface PhraseItem {
  src: string;
  tgt: string;
  translit?: string;
  notes?: string;
}

export interface Lesson {
  /** Composite key: `${pair}:${unit}:${lessonNum}:v${schemaVersion}` */
  id: string;
  pair: string; // e.g. "en-am"
  unit: number;
  lessonNum: number;
  level: "A1" | "A2" | "B1";
  title: string;
  vocab: VocabItem[];
  phrases: PhraseItem[];
  /** "seed" = hand-authored, "ai" = generated by Claude */
  source: "seed" | "ai";
  schemaVersion: number;
  createdAt: number;
}

// ---------------------------------------------------------------------------
// SRS cards (one per vocab item the user has actually seen)
// ---------------------------------------------------------------------------
export interface SrsCard {
  id: string; // `${pair}:${tgt}` — one card per (pair, target word)
  pair: string;
  src: string;
  tgt: string;
  translit?: string;
  // SM-2 fields
  interval: number; // days
  easeFactor: number; // starts at 2.5
  repetitions: number;
  dueDate: number; // unix ms
  lastReviewedAt: number | null;
}

// ---------------------------------------------------------------------------
// Reviews log (every grade ever given — useful for analytics + migration)
// ---------------------------------------------------------------------------
export interface Review {
  id?: number; // auto-increment
  cardId: string;
  grade: 1 | 2 | 3 | 4; // Again / Hard / Good / Easy
  reviewedAt: number;
  intervalAfter: number;
  easeAfter: number;
}

// ---------------------------------------------------------------------------
// Progress (XP, streak, daily counters)
// ---------------------------------------------------------------------------
export interface Progress {
  id: "me";
  xp: number;
  level: number;
  streakDays: number;
  lastActiveDate: string; // YYYY-MM-DD in user's local TZ
  minutesToday: number;
  updatedAt: number;
}

// ---------------------------------------------------------------------------
// DB
// ---------------------------------------------------------------------------
export class LinguaLoopDB extends Dexie {
  settings!: EntityTable<Settings, "id">;
  lessons!: EntityTable<Lesson, "id">;
  cards!: EntityTable<SrsCard, "id">;
  reviews!: EntityTable<Review, "id">;
  progress!: EntityTable<Progress, "id">;

  constructor() {
    super("lingualoop");

    this.version(1).stores({
      settings: "id, updatedAt",
      lessons: "id, pair, [pair+unit+lessonNum], source, createdAt",
      cards: "id, pair, dueDate, [pair+dueDate]",
      reviews: "++id, cardId, reviewedAt",
      progress: "id, lastActiveDate",
    });
  }
}

export const db = new LinguaLoopDB();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
export function pairKey(native: LangCode, target: LangCode): string {
  return `${native}-${target}`;
}

export function lessonId(
  pair: string,
  unit: number,
  lessonNum: number,
  schemaVersion = 1,
): string {
  return `${pair}:${unit}:${lessonNum}:v${schemaVersion}`;
}

export function cardId(pair: string, tgt: string): string {
  return `${pair}:${tgt}`;
}
